### ISSUE TITLE
move mesage to languages files  

### ISSUE THREAD

**Issue by naja7host** [likexian/dnspod-api-php-web#2]
we appreciate your work , nowadays more more people/companies use dnspod arround the world , but the API files has Chinese message languages , it would be nice to add languages system to the API , store languages message in a language file, then add a new line to include the language file . 

best regards

**Comment by likexian** [comment]
Hello naja7host, thanks for your advice, I will try to do this asap.

**Comment by likexian** [comment]
Sorry, no idea up to now, sorry.
