### ISSUE TITLE
内部错误：调用失败

### ISSUE THREAD

**Issue by kaerweinuo** [likexian/dnspod-api-php-web#5]
内部错误：调用失败

**Comment by kaerweinuo** [comment]
估计不是https请求的缘故吧？

**Comment by likexian** [comment]
> 估计不是https请求的缘故吧？

有可能是https的原因，服务器是什么系统，php是什么版本？

**Comment by likexian** [comment]
先看看系统及php是否已支持最新的SSL协议，有问题再联系。

**Comment by cnfug** [comment]
操作失败
内部错误：调用失败

已开启https, php版本 5.6

**Comment by likexian** [comment]
> 操作失败 内部错误：调用失败
> 
> 已开启https, php版本 5.6

php 有 curl 支持吗？windows 系统？

**Comment by cnfug** [comment]
> > 操作失败 内部错误：调用失败
> > 已开启https, php版本 5.6
> 
> php 有 curl 支持吗？windows 系统？

ubuntu 1804, 

cURL support | enabled
cURL Information | 7.70.0

查看了phpinfo有支持的
